version: '2'

services:
  mongodb:
    image: mongo:3.2.11
    volumes:
      - <path to local mongodb data directory>:/data/db
    restart: always
    networks:
      esnet:
        aliases:
          - mongodb

  elasticsearch:
    image: elasticsearch:5.2.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - <path to local elasticsearch data directory>:/usr/share/elasticsearch/data
    restart: always
    environment:
      http.host: 0.0.0.0
    networks:
      esnet:
        aliases:
          - elasticsearch

  searchapi:
    build:
      context: search-api
    volumes:
      - ./search-api:/api
    command: python3 api.py
    ports:
      - 5000:5000
    restart: always
    networks:
      esnet:
        aliases:
          - searchapi

  api:
    build:
      context: api
    ports:
      - 8888:8888
    restart: always
    networks:
      esnet:
        aliases:
          - searchapi

  ui:
    build:
      context: ui
    ports:
      - 5555:80
    volumes:
      - ./ui/html:/var/www/site
    restart: always
    networks:
      esnet:
        aliases:
          - ui

networks:
  esnet:
    driver: bridge
